#!/bin/bash

# This script is used in build_common_coverage.mk and build_unittests.mk files

# Print error message and exit function
function error_exit()
{
    echo "$SCRIPT_NAME: $@"
    exit 1
}


#########################
# --make-coverage mode
#########################

# In this mode script will run "make coverage" command in provided unittest directory
# If "coverage" target doesn't exists in a test Makefile, this test will be skiped
# After running "make coverage" script will find generated JSON files
# List of them will be written to provided file in "append" mode

# Usage: ./coverage_helper.sh --make-coverage TEST_DIR OUT_COVR_DATA_FILE [GCC_BIN]
# TEST_DIR              - Directory with unittest
# OUT_COVR_DATA_FILE    - Output file with list of JSON files found
# GCC_BIN               - Optional GCC compiler binary name (e.g., gcc, gcc-15)
# MAKE (environment)    - Optional make to run in TEST_DIR, "make" by default

# Coverage data file filter for find command
COV_JSON_FIND_FILTER="*_covr.json"
# Folder name where coverage report data is stored
COV_DATA_FOLDER="covr_report"

# Read arguments provided with --make-coverage command
function make_coverage_read_args()
{
    # Check arguments count (2 required, 1 optional)
    if [ $# -lt 2 ] || [ $# -gt 3 ]; then
        error_exit "Usage: $SCRIPT_NAME $COMMAND TEST_DIR OUT_COVR_DATA_FILE [GCC_BIN]"
    fi

    # Set variables
    TEST_DIR=$1
    OUT_COVR_DATA_FILE=$2
    MAKE_GCC_BIN=$3

    # Check for directory exists
    if [ ! -d "$TEST_DIR" ]; then
        error_exit "Directory $TEST_DIR doesn't exist"
    fi

    # `make -n` runs this script too, as the recipe line calls it with $(MAKE):
    # the make of the unittest then only prints its commands, and nothing is
    # written. The first word of MAKEFLAGS holds the single-letter options,
    # it is empty when there are none.
    DRY_RUN=0
    case "${MAKEFLAGS%% *}" in
        -*) ;;
        *n*) DRY_RUN=1 ;;
    esac

    # Check for output file is writable or try to create it
    if [ $DRY_RUN -eq 0 ] && [ ! -w  "$OUT_COVR_DATA_FILE" ]; then
        touch $OUT_COVR_DATA_FILE
        result=$?
        if [ $result -ne 0 ]; then
            error_exit "Unable to create file $OUT_COVR_DATA_FILE"
        fi
    fi
}

# Handler for --make-coverage command
function make_coverage_handler()
{
    cd $TEST_DIR

    # The recipes call this script with MAKE="$(MAKE)": make treats such a line
    # as a recursive make and hands its job slots over in MAKEFLAGS, so under
    # `make -jN` the tests of this unittest are built and run in parallel with
    # the rest of the build. Called from a line without $(MAKE), the make of
    # the unittest may warn "jobserver unavailable: using -j1".
    MAKE=${MAKE:-make}

    # Check for "coverage" target exist in Makefile
    "$MAKE" -qp | $GREP_CMD '^coverage:' > /dev/null
    covr_exist=$?
    if [ $covr_exist -ne 0 ]; then
        echo "Skip test without coverage: $TEST_DIR"
        cd -
        exit 0
    fi

    # Run "make coverage" command for test, passing GCC_BIN if set.
    # COVERAGE_DATA_ONLY=1: the report of the project or submodule is built from
    # the JSON data files of the tests only, so the unittest doesn't generate its
    # own reports (see build_unittests.mk)
    echo "Found test with coverage: $TEST_DIR"
    if [ -n "$MAKE_GCC_BIN" ]; then
        "$MAKE" GCC_BIN=$MAKE_GCC_BIN coverage COVERAGE_DATA_ONLY=1
    else
        "$MAKE" coverage COVERAGE_DATA_ONLY=1
    fi
    covr_result=$?
    if [ $covr_result -ne 0 ]; then
        cd -
        error_exit "$TEST_DIR: make coverage failed"
    fi

    cd -

    if [ $DRY_RUN -eq 1 ]; then
        exit 0
    fi

    # Find JSON files with coverage data which created afrer make coverage command
    json_files=$($FIND_CMD "$TEST_DIR" -type f -name "$COV_JSON_FIND_FILTER")
    if [ -z "$json_files" ]; then
        error_exit "Not found test coverage data in $TEST_DIR"
    fi

    # Write JSON files list to file in append mode
    echo "$json_files" >> $OUT_COVR_DATA_FILE

    exit 0
}

##############################
# --find-uncovered-src mode
##############################

# In this mode script will find uncovered sources by seeking JSON data files generated by gcovr
# List of uncovered files will be written to specified file

# Usage: ./coverage_helper.sh --find-uncovered-src COVR_DATA_FILE OUT_UNCOVR_SRC_FILE SRC_LIST
# COVR_DATA_FILE        - File with list of JSON data files
# OUT_UNCOVR_SRC_FILE   - Output file with list of uncovered sources
# SRC_LIST              - List of source files in project

# Temporary files used for grep
COVERED_SRC_LIST_FILE="covr_src_list.txt"
ALL_SRC_LIST_FILE="src_list.txt"

# Read arguments provided with --find-uncovered-src command
function find_uncovered_src_read_args()
{
    # Check arguments count
    if [ $# -lt 3 ]; then
        error_exit "Usage: $SCRIPT_NAME $COMMAND COVR_DATA_FILE OUT_UNCOVR_SRC_FILE SRC_LIST"
    fi

    # Set variables
    COVR_DATA_FILE=$1; shift
    OUT_UNCOVR_SRC_FILE=$1; shift
    SRC_LIST="$@"

    # Check for data file list exists
    if [ ! -f "$COVR_DATA_FILE" ]; then
        error_exit "File $COVR_DATA_FILE does't exist"
    fi

    # Check for output file is writable or try to create it
    if [ ! -w  "$OUT_UNCOVR_SRC_FILE" ]; then
        touch $OUT_UNCOVR_SRC_FILE
        result=$?
        if [ $result -ne 0 ]; then
            error_exit "Unable to create file $OUT_UNCOVR_SRC_FILE"
        fi
    fi
}

# Handler for --find-uncovered-src command
function find_uncovered_src_handler()
{
    # List of JSON files with coverage data
    json_files_list=$(cat $COVR_DATA_FILE)

    # Find covered source files (find files from $SRC_LIST in JSON files)
    files_found=
    for src_file in $SRC_LIST; do
        for json_file in $json_files_list; do
            if $GREP_CMD -q "\"file\": \"$src_file\"" $json_file; then
                files_found="$files_found $src_file"
                break
            fi
        done
    done

    # Delete first space symbol
    files_found="${files_found# }"

    # Filter-out covered files
    echo "$files_found" | tr ' ' '\n' > $COVERED_SRC_LIST_FILE
    echo "$SRC_LIST" | tr ' ' '\n' > $ALL_SRC_LIST_FILE
    uncovered_src=$($GREP_CMD -Fxv -f $COVERED_SRC_LIST_FILE $ALL_SRC_LIST_FILE)
    rm $COVERED_SRC_LIST_FILE $ALL_SRC_LIST_FILE

    # Save uncovered files list to file
    echo "$uncovered_src" > $OUT_UNCOVR_SRC_FILE

    exit 0
}

##############################
# --gen-uncovered-json mode
##############################

# In this mode script will generate fake JSON data file for uncovered sources
# All lines of uncovered sources will be marked as uncovered

# Usage: ./coverage_helper.sh --gen-uncovered-json UNCOVR_SRC_FILE GCOVR_VER_JSON OUT_UNCOVR_SRC_JSON
# UNCOVR_SRC_FILE       - File with list of uncovered sources
# GCOVR_VER_JSON        - JSON data file generated by gcovr to get "gcovr/format_version" value from it
# OUT_UNCOVR_SRC_JSON   - Output JSON data file with uncovered sources

# Read arguments provided with --gen-uncovered-json command
function gen_uncovered_json_read_args()
{
    # Check arguments count
    if [ $# -ne 3 ]; then
        error_exit "Usage: $SCRIPT_NAME $COMMAND UNCOVR_SRC_FILE GCOVR_VER_JSON OUT_UNCOVR_SRC_JSON"
    fi

    # Set variables
    UNCOVR_SRC_FILE=$1
    GCOVR_VER_JSON=$2
    OUT_UNCOVR_SRC_JSON=$3

    # Check for uncovered sources list file exists
    if [ ! -f "$UNCOVR_SRC_FILE" ]; then
        error_exit "File $UNCOVR_SRC_FILE does't exist"
    fi

    #Check for JSON generated by gcovr exists
    if [ ! -f "$GCOVR_VER_JSON" ]; then
        error_exit "File $GCOVR_VER_JSON does't exist"
    fi

    # Check for output file is writable or try to create it
    if [ ! -w  "$OUT_UNCOVR_SRC_JSON" ]; then
        touch $OUT_UNCOVR_SRC_JSON
        result=$?
        if [ $result -ne 0 ]; then
            error_exit "Unable to create file $OUT_UNCOVR_SRC_JSON"
        fi
    fi
}

# Handler for --gen-uncovered-json command
function gen_uncovered_json_handler()
{
    # Read list of uncovered sourced and parse gcovr/format_version from JSON file
    uncovered_src_list=$(cat $UNCOVR_SRC_FILE)
    gcovr_format_ver=$($GREP_CMD '"gcovr/format_version"' $GCOVR_VER_JSON | $SED_CMD -E 's/.*"gcovr\/format_version": *"([^"]+)".*/\1/')

    # Check for gcovr/format_version sucessfully parsed
    if [ -z "$gcovr_format_ver" ]; then
        error_exit "Unable to get gcovr format version"
    fi

    # Generate JSON data file for all uncovered sources
    echo "{" > $OUT_UNCOVR_SRC_JSON &&
    echo "    \"files\": [" >> $OUT_UNCOVR_SRC_JSON &&
    # Add record to JSON file about each uncovered source file
    for file in $uncovered_src_list; do
        echo "        { \"file\": \"$file\", \"lines\": [" >> $OUT_UNCOVR_SRC_JSON &&
		# Get lines count in $file
        lines_cnt=$(wc -l < $file) &&
		echo "Lines in file $file: $lines_cnt" &&
		# Add record to JSON file about each line
        for line in $(seq 1 $lines_cnt); do
			echo "            { \"branches\": [], \"count\": 0, \"gcovr/noncode\": false, \"line_number\": $line }," >> $OUT_UNCOVR_SRC_JSON
		done &&
		# Delete last ","
        $SED_CMD -i '$s/},/}/' $OUT_UNCOVR_SRC_JSON &&
		echo "        ], \"functions\": [] }," >> $OUT_UNCOVR_SRC_JSON
		# Check for all went fine while generating data for each file
        if [ $? -ne 0 ]; then
            error_exit "Error while generating JSON file"
        fi
    done &&
    # Delete last ","
    $SED_CMD -i '$s/},/}/' $OUT_UNCOVR_SRC_JSON &&
	echo "    ]," >> $OUT_UNCOVR_SRC_JSON &&
	# Add "gcovr/format_version" value
    echo "    \"gcovr/format_version\": \"$gcovr_format_ver\"" >> $OUT_UNCOVR_SRC_JSON &&
	echo "}" >> $OUT_UNCOVR_SRC_JSON

    # Check for all went fine while generating JSON file
    if [ $? -ne 0 ]; then
        error_exit "Error while generating JSON file"
    fi

    exit 0;
}


############################
# --gen-ut-coverage mode
############################

# In this mode script will generate coverage JSON data file and .html report for unit test
# In report there will be only tested source files

# Usage: ./coverage_helper.sh --gen-ut-coverage PROJ_DIR SEARCH_DIR OUT_FILES_BASE_NAME FUNC_MERGE_MODE GCOV_EXECUTABLE [FILTERS_STR]
# PROJ_DIR              - Project root directory
# SEARCH_DIR            - Search directory where gcovr can find .gcno and .gcda files generated after test running
# OUT_FILES_BASE_NAME   - Base name of output files, there will be generated .json and .html files
# FUNC_MERGE_MODE       - Functions merge mode for gcovr
# GCOV_EXECUTABLE       - Path to gcov executable (e.g., gcov, gcov-15)
# FILTERS_STR           - Optional filters string for gcovr to filter only tested source files

# The --gen-ut-coverage-data mode takes the same arguments and generates only the JSON data file

# Read arguments provided with --gen-ut-coverage command
function gen_ut_coverage_read_args()
{
    # Check arguments count
    if [ $# -lt 5 ]; then
        error_exit "Usage: $SCRIPT_NAME $COMMAND PROJ_DIR SEARCH_DIR OUT_FILES_BASE_NAME FUNC_MERGE_MODE GCOV_EXECUTABLE [FILTERS_STR]"
    fi

    # Set variables
    PROJ_DIR=$1; shift
    SEARCH_DIR=$1; shift
    OUT_FILES_BASE_NAME=$1; shift
    FUNC_MERGE_MODE_STR="--merge-mode-functions=$1"; shift
    GCOV_EXECUTABLE=$1; shift
    FILTERS_STR="$@"

    # Check for directory PROJ_DIR exists
    if [ ! -d "$PROJ_DIR" ]; then
        error_exit "Directory $PROJ_DIR doesn't exist"
    fi

    # Check for directory SEARCH_DIR exists
    if [ ! -d "$SEARCH_DIR" ]; then
        error_exit "Directory $SEARCH_DIR doesn't exist"
    fi
}

function get_gcovr_parse_errors_opt()
{
    gcovr_help=$(gcovr --help 2>/dev/null)

    if echo "$gcovr_help" | $GREP_CMD -q "suspicious_hits.warn_once_per_file"; then
        echo "--gcov-ignore-parse-errors=suspicious_hits.warn_once_per_file"
    elif echo "$gcovr_help" | $GREP_CMD -q -- "--gcov-ignore-parse-errors"; then
        # Older gcovr versions accept this option without an explicit value.
        echo "--gcov-ignore-parse-errors"
    fi
}

# Handler for --gen-ut-coverage command
function gen_ut_coverage_handler()
{
    # Set gcov executable option
    GCOV_EXEC_OPT="--gcov-executable $GCOV_EXECUTABLE"
    GCOVR_PARSE_ERRORS_OPT=$(get_gcovr_parse_errors_opt)

    # Generate temporary JSON data file related to project directory
    # gcov runs in the test directory, where the compiler ran: gcovr would try the project root first, and the parallel
    # unit tests race there on the .gcov files of the same sources. The physical path (pwd -P): gcovr builds the paths
    # it gives gcov from the physical cwd, and a logical path through a symlink (/tmp on macOS) leads gcov astray
    gcovr -r $PROJ_DIR --gcov-object-directory "$(pwd -P)" $GCOV_EXEC_OPT $GCOVR_PARSE_ERRORS_OPT $FUNC_MERGE_MODE_STR --json-pretty -o $OUT_FILES_BASE_NAME.json.tmp $SEARCH_DIR &&

    # Generate filtered JSON data without reference to the project directory
    # Temporary data file and filters already have this reference
    cmd="gcovr $GCOV_EXEC_OPT $GCOVR_PARSE_ERRORS_OPT -a $OUT_FILES_BASE_NAME.json.tmp $FILTERS_STR $FUNC_MERGE_MODE_STR --json-pretty -o $OUT_FILES_BASE_NAME.json" &&
    eval "$cmd" &&

    # Remove temporary data file
    rm -f $OUT_FILES_BASE_NAME.json.tmp

    if [ $? -ne 0 ]; then
        error_exit "Error while generating unit test coverage data"
    fi

    # --gen-ut-coverage-data: the JSON data file is all the report of the project needs
    if [ "$GEN_UT_COVERAGE_DATA_ONLY" = 1 ]; then
        exit 0
    fi

    # Generate .html report and print coverage information
    gcovr -r $PROJ_DIR $GCOV_EXEC_OPT $GCOVR_PARSE_ERRORS_OPT -a $OUT_FILES_BASE_NAME.json $FUNC_MERGE_MODE_STR --html-details $OUT_FILES_BASE_NAME.html &&
    # Generate XML report (Cobertura format)
    gcovr -r $PROJ_DIR $GCOV_EXEC_OPT $GCOVR_PARSE_ERRORS_OPT -a $OUT_FILES_BASE_NAME.json $FUNC_MERGE_MODE_STR --cobertura-pretty -o $COV_DATA_FOLDER/coverage.cobertura.xml &&
    # Generate lcov.info file
    gcovr -r $PROJ_DIR $GCOV_EXEC_OPT $GCOVR_PARSE_ERRORS_OPT -a $OUT_FILES_BASE_NAME.json $FUNC_MERGE_MODE_STR --lcov -o $COV_DATA_FOLDER/lcov.info &&
    gcovr -s -r $PROJ_DIR $GCOV_EXEC_OPT $GCOVR_PARSE_ERRORS_OPT -a $OUT_FILES_BASE_NAME.json $FUNC_MERGE_MODE_STR

    # Check for all went fine while generating coverage data and report
    if [ $? -ne 0 ]; then
        error_exit "Error while generating unit test coverage data and report"
    fi

    exit 0
}


##################
#   Main progam
##################

UNAME_S=$(uname -s)
if [ "$UNAME_S" = "Darwin" ]; then
    # macOS - use GNU tools if available, fallback to BSD versions
    SED_CMD=$(which gsed 2>/dev/null || which sed)
    GREP_CMD=$(which ggrep 2>/dev/null || which grep)
    FIND_CMD=$(which gfind 2>/dev/null || which find)
else
    # Linux systems
    SED_CMD=sed
    GREP_CMD=grep
    FIND_CMD=find
fi

# Get script file name and command directive
SCRIPT_NAME=$0
COMMAND=$1
shift

# Check if command not provided
if [ -z "$COMMAND" ]; then
    error_exit "No parameters passed"
fi

# Handle requested command
case "$COMMAND" in
    --make-coverage)        make_coverage_read_args $@
                            make_coverage_handler;;
    --find-uncovered-src)   find_uncovered_src_read_args $@
                            find_uncovered_src_handler;;
    --gen-uncovered-json)   gen_uncovered_json_read_args $@
                            gen_uncovered_json_handler;;
    --gen-ut-coverage)      gen_ut_coverage_read_args $@
                            gen_ut_coverage_handler;;
    --gen-ut-coverage-data) gen_ut_coverage_read_args $@
                            GEN_UT_COVERAGE_DATA_ONLY=1
                            gen_ut_coverage_handler;;
    *)                      error_exit "Unknown command $COMMAND";;
esac

# Emergency exit, handlers should provide correct exit code
exit 1
